[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install',
  'cd client && npm install && npm run build'
]

[phases.build]
cmds = []

[start]
cmd = 'node server/index.js'

[staticAssets]
'client/build' = '/'

